### ISSUE TITLE
Text-To-Speech Module

### ISSUE THREAD

**Issue by chidiewenike** [calpoly-csai/swanton#1]
## Objective
Explore offline Text-To-Speech (TTS) libraries that will convert a string to audio.

## Key Result
Create a function that will output raw audio bytes from a string input.

## Details
The function will take, as input, a string which will be the output from Rasa. The string is then converted to raw audio bytes by an offline/local TTS library. When selecting the appropriate library, priorities are as follows:

1. Memory
2. Runtime
3. Speaker Quality
4. Customizability of sound properties

**Comment by mfekadu** [comment]
useful comment in issue #2 

https://github.com/calpoly-csai/swanton/issues/2#issuecomment-664071466

**Comment by nguyenlienviet** [comment]
The [pyttsx3](https://pyttsx3.readthedocs.io/en/latest/engine.html#examples) library is offline and doesn't seem to use much memory. However, it doesn't have a method to return audio bytes and only has a method to play the audio instead; would this work for our use case @chidiewenike ?. I'm not sure if it will work out of the box on the pi, but it's very easy to use so you can just try on your pi.

**Comment by gwholland3** [comment]
It can also save the audio to a file, in mp3 format I believe. Would that help?

**Comment by chidiewenike** [comment]
Playing the audio within the function using the pyttsx3 module is fine.
