### ISSUE TITLE
Analyze Deepspeech Feedback Transcriptions

### ISSUE THREAD

**Issue by chidiewenike** [calpoly-csai/swanton#32]
## Objective
Generate a dataset of feedback users could give to the chatbot and log its transcription. 

## Key Result
A CSV with the ground-truth feedback and how the feedback was transcribed using Deepspeech.

## Details
We want to obtain feedback from users to analyze the user experience and make improvements. One solution is to store the raw audio response and pull that data for analysis. An issue with this is that audio data is large in comparison to text and transferring this data could take a long time. The easiest thing to do would be to transcribe that audio to text and logging the data. 

You will need the following [DeepSpeech model](https://github.com/mozilla/DeepSpeech/releases/download/v0.8.1/deepspeech-0.8.1-models.pbmm) and [DeepSpeech scorer](https://github.com/mozilla/DeepSpeech/releases/download/v0.8.1/deepspeech-0.8.1-models.scorer) to use run_stt. Ensure that these files are in the same directory as the stream_deepspeech.py program.

**Example of feedback dialogue:**
_Chatbot_: "Would you like to provide feedback about your experience?"
_User_: "Sure."
_Chatbot_: "Okay, please let me know how your experience was."
_User_: "Um..." *Pauses for 3 seconds to think* "My experience was good. The assistant answered my question and also shared something about the Cheese House that I did not know"

(The last user response is the type of feedback data you will need to generate and test Deepspeech with.)

**Comment by gwholland3** [comment]
Is this issue closed now?

**Comment by chidiewenike** [comment]
The results of the issue can be found here: 
[Deepspeech Feedback Transcriptions](https://docs.google.com/spreadsheets/d/1xfnPtXyh5NcId_eo511CUWIdQLjjVDWT2BJ39Z6JWgg/edit?usp=sharing)
