### ISSUE TITLE
Log Queries to Google Sheets

### ISSUE THREAD

**Issue by chidiewenike** [calpoly-csai/swanton#35]
## Objective
Log user queries to a shared Google Sheets page to analyze user experiences and make improvements in both the UX and NLP model.

## Key Result
Create two separate functions:

1. First function must setup the Google Sheets API service with the necessary configs.
2. The second function must take the user's question and the system's answer & log it on a single row of a Google Sheets page with a timestamp of the log entry. 

## Details
You can use [this tutorial](https://medium.com/analytics-vidhya/how-to-read-and-write-data-to-google-spreadsheet-using-python-ebf54d51a72c) to achieve the required functionality for this program.

To log entries to a Google Sheet page, you will need to use the [Google Sheets API](https://developers.google.com/sheets/api/quickstart/python). 

To use the Google Sheets API, you will need an authentication JSON and Google Sheet ID. Make the strings for the path to the authentication JSON and Google Sheet ID constants in the script which the function resides. 

A log entry row will look as follows:

|                      Question                            |                 Answer                 |              Timestamp             |
 "How big is Swanton Pacific Ranch?"                  " 3200 acres "                    "12/22/2020 12:45:23"

**Comment by gwholland3** [comment]
Does the second function take a timestamp argument of when the question was actually asked by the user along with the question and answer, or does it use the system time to generate a timestamp within the function?

**Comment by chidiewenike** [comment]
The latter. We can use the system time within the function through the datetime library or time library.

**Comment by chidiewenike** [comment]
You will be appending to the Google Sheet. There is an appending example on the Google Sheets API page. https://developers.google.com/sheets/api/guides/values#python_2

**Comment by gwholland3** [comment]
Do you have the Google Sheet I'll be writing to?

**Comment by chidiewenike** [comment]
We will soon. When we do, you can just change the Google Sheet ID and auth path constants.
